// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  Cybersecuritebar: [
    {
      type: 'category',
      label: 'Cybersécurité',
      items: ['01 Cybersécurité/Intro Cybersécurité',
        '01 Cybersécurité/Bases_de_la_cybersecurité'
      ],
    },
  ],

  Informatiquebar: [
    {
      type: 'category',
      label: 'Informatique et réseau',
      items: ['02 informatique et réseau/Intro Informatique et réseau'],
    },
  ],
  electroniquebar: [
    {
      type: 'category',
      label: 'Electronique',
      items: ['03 Electronique/Intro electronique',
        '03 Electronique/Arduino',
      ],
    },
  ],
   
};

export default sidebars;
